In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Acapulco,MX,2021-01-27 01:21:41,16.8634,-99.8901,77.04,75,7,5.53
1,1,Rikitea,PF,2021-01-27 01:22:13,-23.1203,-134.9692,80.55,70,24,9.04
2,2,Saint-Philippe,RE,2021-01-27 01:25:55,-21.3585,55.7679,75.20,57,0,6.91
3,3,Hermanus,ZA,2021-01-27 01:25:55,-34.4187,19.2345,62.01,93,69,3.33
4,4,Kapaa,US,2021-01-27 01:25:55,22.0752,-159.3190,77.00,78,90,14.97

In [3]:
# Configure gmaps to use your Google API Key.
gmaps.configure(api_key=g_key)

In [4]:
# Heatmap of temperature
# Get the latitude and longtitude.
location = city_data_df[['Lat',"Lng"]]

# Get the maximum temperature.
max_temp = city_data_df['Max Temp']
temps = []
for temp in max_temp:
    temps.append(max(temp,0))

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(location, weights=temps, dissipating=False, max_intensity=300, point_radius=4)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# Heatmap of percent humidity
locations = city_data_df[['Lat', 'Lng']]
humidity = city_data_df['Humidity']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(location, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)

# Call the figure to plot the data
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
# Heatmap of percent Windspeed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [10]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Acapulco,MX,2021-01-27 01:21:41,16.8634,-99.8901,77.04,75,7,5.53
1,1,Rikitea,PF,2021-01-27 01:22:13,-23.1203,-134.9692,80.55,70,24,9.04
2,2,Saint-Philippe,RE,2021-01-27 01:25:55,-21.3585,55.7679,75.20,57,0,6.91
4,4,Kapaa,US,2021-01-27 01:25:55,22.0752,-159.3190,77.00,78,90,14.97
8,8,Makakilo City,US,2021-01-27 01:25:56,21.3469,-158.0858,80.60,54,75,12.66
9,9,Mataura,NZ,2021-01-27 01:22:11,-46.1927,168.8643,75.99,50,100,10.00
11,11,Atuona,PF,2021-01-27 01:25:18,-9.8000,-139.0333,78.48,77,0,16.33
14,14,Sambava,MG,2021-01-27 01:25:20,-14.2667,50.1667,75.20,86,13,4.81
16,16,Bengkulu,ID,2021-01-27 01:24:52,-3.8004,102.2655,76.10,81,100,1.90
19,19,Kaili,ID,2021-01-27 01:25:58,-3.4626,120.2147,76.35,72,100,1.63

In [11]:
# Create a DataFrame called hotel_df to store hotel names along with city, country, max_temp, and coordinates.
hotel_df = preferred_cities_df[['City', 'Country', 'Max Temp', 'Lat', 'Lng']].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

              City Country  Max Temp      Lat       Lng Hotel Name
0         Acapulco      MX     77.04  16.8634  -99.8901
1          Rikitea      PF     80.55 -23.1203 -134.9692
2   Saint-Philippe      RE     75.20 -21.3585   55.7679
4            Kapaa      US     77.00  22.0752 -159.3190
8    Makakilo City      US     80.60  21.3469 -158.0858
9          Mataura      NZ     75.99 -46.1927  168.8643
11          Atuona      PF     78.48  -9.8000 -139.0333
14         Sambava      MG     75.20 -14.2667   50.1667
16        Bengkulu      ID     76.10  -3.8004  102.2655
19           Kaili      ID     76.35  -3.4626  120.2147

In [12]:
# Set the parameters to search for a hotel.
params = {
    'radius': 10000,
    'type': 'lodging',
    'key': g_key
}

In [13]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.

In [14]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Acapulco,MX,77.04,16.8634,-99.8901,HS Hotsson Smart Acapulco
1,Rikitea,PF,80.55,-23.1203,-134.9692,Pension Maro'i
2,Saint-Philippe,RE,75.20,-21.3585,55.7679,p'ti case d'éléna
4,Kapaa,US,77.00,22.0752,-159.3190,Sheraton Kauai Resort at Coconut Beach
8,Makakilo City,US,80.60,21.3469,-158.0858,Marriott's Ko Olina Beach Club
9,Mataura,NZ,75.99,-46.1927,168.8643,Southland Organic Farmstay
11,Atuona,PF,78.48,-9.8000,-139.0333,Villa Enata
14,Sambava,MG,75.20,-14.2667,50.1667,Melrose
16,Bengkulu,ID,76.10,-3.8004,102.2655,Grage Hotel Bengkulu
19,Kaili,ID,76.35,-3.4626,120.2147,Salu Lompo

In [15]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)

marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [18]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [19]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))